/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package recuento_horas;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.sql.Connection;
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author javie
 */
public class Introducir_datos extends PANTALLA{

    /**
     * Creates new form Introducir_datos
     */
    public Introducir_datos() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timingTargetAdapter1 = new org.jdesktop.animation.timing.TimingTargetAdapter();
        timingTargetAdapter2 = new org.jdesktop.animation.timing.TimingTargetAdapter();
        timingTargetAdapter3 = new org.jdesktop.animation.timing.TimingTargetAdapter();
        nombre_texto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        actividad = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        accion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        modelo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        empresa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        interlocutor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        temas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hora_inicial = new javax.swing.JComboBox<>();
        hora_final = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        proyecto = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 153));

        nombre_texto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marino", "Juanjo", "Iñigo" }));
        nombre_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_textoActionPerformed(evt);
            }
        });

        jLabel1.setText("PERSONA");

        jLabel2.setText("HORA INICIAL");

        jButton1.setText("ENVIAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jToggleButton1.setText("ATRÁS");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        actividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Difusión", "Formación", "Evaluación", "Gala", "Interna", "Gob. de Navarra", "Formación int", "Patronato", "CEX", "Consejo Dirección", "Club Evaluación", "Consultores" }));

        jLabel3.setText("ACTIVIDAD");

        jLabel4.setText("ACCIÓN");

        accion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gestión", "Reunión", "Jornada-Charla", "Visita/R/J", "Formación", "Otros" }));
        accion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionActionPerformed(evt);
            }
        });

        jLabel5.setText("MODELO");

        modelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EFQM", "Gestión Avanzada", "5S", "Todos", "Otros" }));
        modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloActionPerformed(evt);
            }
        });

        jLabel6.setText("EMPRESA");

        empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaActionPerformed(evt);
            }
        });

        jLabel7.setText("INTERLOCUTOR");

        jLabel8.setText("TEMAS TRATADOS");

        temas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temasActionPerformed(evt);
            }
        });

        jLabel9.setText("HORA FINAL");

        hora_inicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06:00", "06:30", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30", "24:00" }));
        hora_inicial.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hora_inicialItemStateChanged(evt);
            }
        });
        hora_inicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hora_inicialActionPerformed(evt);
            }
        });

        hora_final.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06:00", "06:30", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30", "24:00" }));
        hora_final.setSelectedIndex(6);
        hora_final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hora_finalActionPerformed(evt);
            }
        });
        hora_final.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                hora_finalKeyPressed(evt);
            }
        });

        jLabel10.setText("PROYECTO");

        proyecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Industria", "Funcionamiento interno", "CEX", "Transformación digital", "Gobierno", "Universidades", "Otros proyectos" }));
        proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proyectoActionPerformed(evt);
            }
        });

        jLabel11.setText("FECHA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(temas, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(empresa)
                                .addComponent(interlocutor, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hora_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hora_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(actividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addContainerGap(94, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(accion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(actividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(interlocutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hora_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(hora_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(temas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jToggleButton1))))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_textoActionPerformed
        // DESPEGLABLE NOMBRE
        

    }//GEN-LAST:event_nombre_textoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // BOTON OK
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // BOTON OK CLICK
        
        Trabajadores new_trabajador = anyadirtrabajador();
        
        
        
        try {
            try {
                enviar_datos(new_trabajador);
            } catch (SQLException ex) {
                Logger.getLogger(Introducir_datos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ParseException ex) {
            Logger.getLogger(Introducir_datos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        

        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // RETURN BUTTON
        
        this.dispose();
        MENU m1 = new MENU();
        m1.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empresaActionPerformed

    private void temasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temasActionPerformed

    private void hora_inicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hora_inicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hora_inicialActionPerformed

    private void hora_finalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hora_finalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hora_finalActionPerformed

    private void modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloActionPerformed

    private void proyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proyectoActionPerformed

    private void accionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accionActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        
         Trabajadores new_trabajador = anyadirtrabajador();
        clearData();
        
        
        try {
             try {
                 enviar_datos(new_trabajador);
             } catch (SQLException ex) {
                 Logger.getLogger(Introducir_datos.class.getName()).log(Level.SEVERE, null, ex);
             }
        } catch (ParseException ex) {
            Logger.getLogger(Introducir_datos.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void hora_finalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hora_finalKeyPressed
        // TODO add your handling code here:
             if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        
         Trabajadores new_trabajador = anyadirtrabajador();
        clearData();
        
        
        try {
             try {
                 enviar_datos(new_trabajador);
             } catch (SQLException ex) {
                 Logger.getLogger(Introducir_datos.class.getName()).log(Level.SEVERE, null, ex);
             }
        } catch (ParseException ex) {
            Logger.getLogger(Introducir_datos.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    
        
    }//GEN-LAST:event_hora_finalKeyPressed

    private void hora_inicialItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_hora_inicialItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
          // Get the selected item of comboBox1
          String selectedItem = (String) evt.getItem();
          // Set the selected item of comboBox2 based on the selected item of comboBox1
          System.out.println(selectedItem);
          
          //Convert string to time
          String timeString = selectedItem;
          DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm");
          LocalTime time = LocalTime.parse(timeString, formatter);
          System.out.println(time);
          
          //Add 3 hours
          LocalTime newTime = time.plusHours(3);
          System.out.println(newTime);
          hora_final.setSelectedItem(newTime.toString());
         /* if (selectedItem.equals("Item 1")) {
            hora_final.setSelectedItem("Item A");
          } else if (selectedItem.equals("Item 2")) {
            hora_final.setSelectedItem("Item B");
          } else if (selectedItem.equals("Item 3")) {
            jhora_final.setSelectedItem("Item C");
          }*/
        }
    }//GEN-LAST:event_hora_inicialItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ParseException {
        /* Set the Nimbus look and feel */
        
    

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Introducir_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Introducir_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Introducir_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Introducir_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Introducir_datos().setVisible(true);
                
                
            }
        });
    }
    
    
    
    public Trabajadores anyadirtrabajador(){
        int res = JOptionPane.showConfirmDialog(null, "¿ESTÁ SEGURO QUE DESEA ENVIAR LOS DATOS?","CONFIRMAR ENVIO", JOptionPane.YES_NO_OPTION);
        if(res==0){
        
        //Get data from form
        String nombre_introducido = nombre_texto.getSelectedItem().toString();
        
       // double horas_trabajadas = Double.parseDouble(horas_introducidas.getText());

        String hora_ini = hora_inicial.getSelectedItem().toString();
        String hora_fin = hora_final.getSelectedItem().toString();
        String actividad_ = actividad.getSelectedItem().toString();
        String modelo_ = modelo.getSelectedItem().toString();
        String accion_ = accion.getSelectedItem().toString();
        String empresa_ = empresa.getText();
        String interlocutor_ = interlocutor.getText();
        String temas_ = temas.getText();
        String proyecto_ = proyecto.getSelectedItem().toString();
        
        
        
        
        
        Date fecha = jDateChooser1.getDate();
        
        String mes = null;
        String ano = null;
        
        if (fecha == null){
            
            
            JOptionPane.showMessageDialog(null, "POR FAVOR RELLENE TODOS LOS CAMPOS");
            return null;
        
        } 
        
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd"); 
        String short_date = formatter.format(fecha);
        
        
        
        // crear un objeto Trabajador y añadir atributos
       Trabajadores trab1 = new Trabajadores(nombre_introducido);
       //trab1.setHoras(horas_trabajadas);
       trab1.setFechaCorta(short_date);
       trab1.setFechaLarga(fecha);
       
       trab1.setHoraInicial(hora_ini);
       trab1.setHoraFinal(hora_fin);
       trab1.setActividad(actividad_);
       trab1.setModelo(modelo_);
       trab1.setAccion(accion_);
       trab1.setEmpresa(empresa_);
       trab1.setInterlocutor(interlocutor_);
       trab1.setTemas(temas_);
       trab1.setProyecto(proyecto_);
  
       
       
       
       System.out.println(nombre_introducido);
       //System.out.println(horas_trabajadas);
       System.out.println(short_date);
       //System.out.println(trab1.getFechaLarga());
      // System.out.println(hora_final);
       
       
       return trab1;
        }
        return null;
        
        
        
        
}
public void enviar_datos(Trabajadores trab1) throws ParseException, SQLException{
            PreparedStatement prep_statement = null;
            if (trab1==null){
                return;
            }
            clearData();
            Connection con = Conectar_db.conectDB();
            try {
                
                
    
            String sql = "insert into ficha (nombre, HORA_INICIO, HORA_FIN, TIEMPO_DEDICADO, FECHA, PROYECTO, ACTIVIDAD, ACCIÓN, MODELO, EMPRESA, INTERLOCUTOR, TEMAS_TRATADOS, MES, ANO) values( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            
            
            
            prep_statement = con.prepareStatement(sql);
            
            prep_statement.setString(1, trab1.getNombre() );
            prep_statement.setString(2, trab1.getHoraInicial());
            prep_statement.setString(3, trab1.getHoraFinal());
            prep_statement.setString(4, trab1.getHorasTrabajadas());
            prep_statement.setString(5, trab1.getFechaCorta());
            
            prep_statement.setString(6, trab1.getProyecto());
            prep_statement.setString(7, trab1.getActividad());
            prep_statement.setString(8, trab1.getAccion());
            prep_statement.setString(9, trab1.getModelo());
            prep_statement.setString(10, trab1.getEmpresa());
            prep_statement.setString(11, trab1.getInterlocutor());
            prep_statement.setString(12, trab1.getTemas());
            prep_statement.setInt(13, trab1.mes_desdeFecha());
            prep_statement.setInt(14, trab1.ano_desdefecha());
            
            prep_statement.execute();
            
            
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }finally {
            prep_statement.close();
            con.close();
            System.out.println("Connection closed");
            
        }
}
        public void clearData(){
        
            
            empresa.setText(" ");
            interlocutor.setText(" ");
            
            temas.setText(" ");
            //empresa.setText(" ");
        
        }
    
    
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> accion;
    private javax.swing.JComboBox<String> actividad;
    private javax.swing.JTextField empresa;
    private javax.swing.JComboBox<String> hora_final;
    private javax.swing.JComboBox<String> hora_inicial;
    private javax.swing.JTextField interlocutor;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<String> modelo;
    private javax.swing.JComboBox<String> nombre_texto;
    private javax.swing.JComboBox<String> proyecto;
    private javax.swing.JTextField temas;
    private org.jdesktop.animation.timing.TimingTargetAdapter timingTargetAdapter1;
    private org.jdesktop.animation.timing.TimingTargetAdapter timingTargetAdapter2;
    private org.jdesktop.animation.timing.TimingTargetAdapter timingTargetAdapter3;
    // End of variables declaration//GEN-END:variables
}
